package io.github.bluestormdna.kocoboy.core

import io.github.bluestormdna.kocoboy.host.Host
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout

// Writes docs/TESTS.md: KOCOBOY_TEST_PAGE=1 ./gradlew :kocoboy-core:jvmTest --tests '*TestStatusPage*' --rerun
class TestStatusPage {

    private val docs = File("../docs")

    private class Row(val path: String, val result: RomResult, val screen: String?) {
        val name = path.substringAfterLast('/').removeSuffix(".gb")
        val folder = path.substringBeforeLast('/')

        // Mooneye names end with the models a test was verified on, blargg's interrupt_time is CGB only
        private val models = name.substringAfterLast('-', "")
        val otherHardware = path == "blargg/interrupt_time/interrupt_time.gb" ||
            (path.startsWith("mooneye/") && models != "" && "dmgABC" !in models && 'G' !in models)

        val mark = when {
            result == RomResult.PASS -> "✅"
            otherHardware -> "➖"
            result == RomResult.INCONCLUSIVE -> "⏳"
            else -> "❌"
        }
    }

    @Test
    fun write() {
        if (System.getenv("KOCOBOY_TEST_PAGE") == null) return
        val rows = listOf("mooneye", "blargg").flatMap { suite ->
            val root = resource("roms/$suite")
            root.walkTopDown().filter { it.extension == "gb" }.sortedBy { it.path }.map { file ->
                val path = "$suite/${file.relativeTo(root).path}"
                val run = runRomWithScreen(file.readBytes())
                Row(path, run.result, run.screen?.let { save(it, path) })
            }.toList()
        }
        docs.resolve("TESTS.md").writeText(page(rows, acid2()))
    }

    private fun page(rows: List<Row>, acid2Matches: Boolean): String {
        fun passed(group: List<Row>) = group.count { it.result == RomResult.PASS }
        fun count(group: List<Row>, label: String): String {
            val tests = group.filterNot { it.otherHardware }
            val other = (group.size - tests.size).takeIf { it > 0 } ?: ""
            return "| $label | ${passed(tests)} / ${tests.size} | $other |"
        }
        val dmg = rows.filterNot { it.otherHardware }
        val folders = rows.groupBy { it.folder }
        val byFolder =
            folders.map { (folder, group) -> count(group, "`$folder`") } + count(rows, "**Total**")
        val everyTest = folders.map { (folder, group) ->
            val tests = group.joinToString("\n") { row ->
                val screen = row.screen?.let { "![${row.name}]($it)" } ?: "no output"
                "| ${row.name} | ${row.mark} | $screen |"
            }
            "### `$folder`\n\n| Test | Result | Screen |\n|---|---|---|\n$tests"
        }
        val passedDmg = passed(dmg)
        val otherHardware = rows.size - dmg.size
        val verdict = if (acid2Matches) "Every pixel matches" else "**Does not match**"
        return """
            ># Test status
            >
            >Generated by running every test ROM in `kocoboy-core/src/jvmTest/resources/roms`, do not edit by hand. Regenerate with
            >
            >```
            >KOCOBOY_TEST_PAGE=1 ./gradlew :kocoboy-core:jvmTest --tests '*TestStatusPage*' --rerun
            >```
            >
            >Kocoboy emulates the original Game Boy (DMG). It passes **$passedDmg of ${dmg.size}** DMG test ROMs, $otherHardware more check other models and are expected to fail.
            >
            >## dmg-acid2
            >
            >| Kocoboy | Reference |
            >|---|---|
            >| ![Kocoboy](tests/dmg-acid2.png) | ![Reference](tests/dmg-acid2-reference.png) |
            >
            >$verdict the reference.
            >
            >## By folder
            >
            >| Folder | Passed | Other hardware |
            >|---|---|---|
            >${byFolder.joinToString("\n")}
            >
            >## Every test
            >
            >${everyTest.joinToString("\n\n")}
        """.trimMargin(">") + "\n"
    }

    // Frame 60 of dmg-acid2 against the reference, compared by shade since the palettes differ
    private fun acid2(): Boolean {
        val frame = CompletableDeferred<IntArray>()
        val emulator = Emulator(
            object : Host {
                var frames = 0

                override fun render(frameBuffer: IntArray) {
                    if (++frames == 60) frame.complete(frameBuffer.copyOf())
                }

                override fun play(sampleBuffer: ByteArray) {}
            },
        )
        emulator.loadRom(resource("roms/dmg-acid2/dmg-acid2.gb").readBytes())
        emulator.runUncapped()
        val screen = runBlocking { withTimeout(10_000) { frame.await() } }
        emulator.powerOff()
        save(screen, "dmg-acid2")
        val reference = resource("roms/dmg-acid2/reference-dmg.png")
        reference.copyTo(docs.resolve("tests/dmg-acid2-reference.png"), overwrite = true)
        val expected = ImageIO.read(reference).getRGB(0, 0, 160, 144, null, 0, 160)
        return shades(screen).contentEquals(shades(expected))
    }

    // Brightness rank of each pixel, the green channel orders both the DMG and the gray palette
    private fun shades(pixels: IntArray): IntArray {
        val ranked = pixels.distinct().sortedBy { it shr 8 and 0xFF }
        return IntArray(pixels.size) { ranked.indexOf(pixels[it]) }
    }

    // A screen of one color is no output
    private fun save(pixels: IntArray, path: String): String? {
        if (pixels.all { it == pixels[0] }) return null
        val file = docs.resolve("tests/${path.removeSuffix(".gb").replace(' ', '_')}.png")
        file.parentFile.mkdirs()
        val image = BufferedImage(160, 144, BufferedImage.TYPE_INT_RGB)
        image.setRGB(0, 0, 160, 144, pixels, 0, 160)
        ImageIO.write(image, "png", file)
        return file.relativeTo(docs).path
    }

    private fun resource(path: String) = File(javaClass.classLoader.getResource(path)!!.toURI())
}
